language: python
python:
    - "3.8"
service:
  - docker
before_install:
  docker build -t tommywenjiezhang/group-calculator .
script:
  docker run tommywenjiezhang/group-calculator
after_success:
  - codecov