language: python
python:
    - "3.8"
service:
  - docker
before_install:
  docker build -t tommywenjiezhang/group-calculator .
script:
  - ci_post_cov="bash <(curl -s https://codecov.io/bash) -t $token"
  - ci_env="bash <(curl -s https://codecov.io/env)"
  - docker run tommywenjiezhang/group-calculator /bin/bash -c "$ci_env && coverage run -m unittest && $ci_post_cov"