language: python
python:
    - "3.8"
service:
  - docker
before_install:
  docker build -t tommywenjiezhang/group-calculator .
script:
  docker run --name groupcalculator tommywenjiezhang/group-calculator
after_success:
  - bash <(curl -s https://codecov.io/bash)